Controllers
c3c1l1a/rails_blog pull request #4
Opened 2022-10-04 13:00 UTC by c3c1l1a

The aim of this pull request is to create controllers and views for the Blog app

## What was accomplished 
Added these routes and their respective controllers and placeholder views
![image](https://user-images.githubusercontent.com/8858461/193825127-4f18bf53-07bb-47d3-861d-b546cc9e18db.png)
![image](https://user-images.githubusercontent.com/8858461/193825254-a152bf57-ead0-4314-b959-1e9310b1ec5c.png)

`rails routes` command outputs 
![image](https://user-images.githubusercontent.com/8858461/193825493-ed38b4e0-b213-48cc-bfd0-ed54b4ac704f.png)

## Checklist
-    [Linting tests](https://github.com/microverseinc/linters-config) pass locally with my changes
-    Used correct [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md)
-    Documentation is done in a [professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)

2022-10-04 13:38 UTC, alexander16108 requested changes
Hi @c3c1l1a , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
soo close 👍🏾  💯 

<img src="https://media3.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif" style="height:50px"/> 

## Highlights
clean code✔️ 
passing linters ✔️ 
met all the requirements ❌ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-04 13:38 UTC, alexander16108 commented on app/controllers/posts_controller.rb
> +end
your post_controller should have  an index action as part of the project requirement  🥂

2022-10-04 13:38 UTC, alexander16108 commented on app/controllers/users_controller.rb
> +  def show; end
your user_controller should have  an index action as part of the project requirement  🥂

2022-10-04 13:38 UTC, alexander16108 commented on config/routes.rb
>  end
the routes for your application should typically look like this 
`
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end
`
for more details [visit this page on rails routing and configuring the rails router](https://guides.rubyonrails.org/routing.html)

2022-10-05 08:07 UTC, gemmen29 approved these changes
Hi @c3c1l1a, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-05 10:41 UTC, merged